### ISSUE TITLE
lzo gem 0.1.0 fails to load under Ruby 2.6.0

### ISSUE THREAD

**Issue by jeffkirk1** [aidansteele/lzo#2]
I'm attempting to port a script written for Ruby 2.4.1 to 2.6.0 to try the JIT compiler. Unfortunately the lzo 0.1.0 gem errors out with the error "NameError (field 'filter' is a reserved name in BinData::Struct). Below is the stack trace. 

Verified using Ruby 2.6.0 (built with RVM) on macOS 10.14.1 Mojave (build 18B75), macOS 10.14.2 (build 1BC54), and CentOS 7.4.1708.

Happy to provide any additional info.

```
jeff-imac:connection_collector_2_6 jeff.kirk$ irb
2.6.0 :001 > puts RUBY_VERSION
2.6.0
 => nil
2.6.0 :002 > require 'lzo'
Traceback (most recent call last):
       16: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/lzo-0.1.0/lib/lzo/lzop.rb:7:in `<top (required)>'
       15: from /Users/jeff.kirk/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
       14: from /Users/jeff.kirk/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
       13: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/lzo-0.1.0/lib/lzo/lzop/header.rb:1:in `<top (required)>'
       12: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/lzo-0.1.0/lib/lzo/lzop/header.rb:2:in `<module:LZO>'
       11: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/lzo-0.1.0/lib/lzo/lzop/header.rb:3:in `<module:LZOP>'
       10: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/lzo-0.1.0/lib/lzo/lzop/header.rb:9:in `<class:Header>'
        9: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/bindata-2.4.3/lib/bindata/dsl.rb:46:in `method_missing'
        8: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/bindata-2.4.3/lib/bindata/dsl.rb:120:in `method_missing'
        7: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/bindata-2.4.3/lib/bindata/dsl.rb:181:in `parse_and_append_field'
        6: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/bindata-2.4.3/lib/bindata/dsl.rb:181:in `new'
        5: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/bindata-2.4.3/lib/bindata/dsl.rb:343:in `initialize'
        4: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/bindata-2.4.3/lib/bindata/dsl.rb:361:in `params_from_field_declaration'
        3: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/bindata-2.4.3/lib/bindata/dsl.rb:388:in `params_from_block'
        2: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/bindata-2.4.3/lib/bindata/dsl.rb:388:in `instance_eval'
        1: from /Users/jeff.kirk/.rvm/gems/ruby-2.6.0@connection_collector_2_6/gems/lzo-0.1.0/lib/lzo/lzop/header.rb:16:in `block in <class:Header>'
NameError (field 'filter' is a reserved name in BinData::Struct)
```

**Comment by jeffkirk1** [comment]
I also tested this against the newer bindata gem version 2.4.4 with the same result.

**Comment by kylekyle** [comment]
It looks like this is fixed now. Any chance you could cut a release for us 2.6 users?
